[cli]: better error message when calling logs command without a deployment url (#11877)
### 🧐 What's in there?

`vc logs` command requires a deployment id or url (could we considering
to default to the current prod deployment in the future?)
Right now users are getting an infamous error message:

```shell
▲  vc logs
Vercel CLI 35.0.3
Error: An unexpected error occurred in logs: TypeError: Cannot read properties of undefined (reading 'includes')
```

This PR handles that case better and show the appropriate disclaimer in
addition to the command help.

### 🧪 How to test?

It's covered by unit tests.
To try it live:
- `pnpm build`
- `pnpm -F vercel dev logs`
> yields: Error: `vercel logs <deployment>` expects exactly one argument