chore(vercel): skip failing test (#13436)
This test is correctly failing.

Only doing this to unblock others since I have 3 hrs of meetings and
we've already released this broken behavior:
```
$ vercel dev -t *** --scope ***
Vercel CLI 42.3.0
> Installing Builder: @vercel/does-not-exist
Error: The package `@vercel/does-not-exist` is not published on the npm registry
Learn More: https://vercel.link/builder-dependencies-install-failed
# `vercel dev` never exits
```

---------

Co-authored-by: Trek Glowacki <trek.glowacki@vercel.com>