Go work missing go version declaration in dev mode (#12574)
The go.work file used on `vercel dev` is missing the go version
declaration causing 502 errors on functions in dev that work as expected
in production.

discussed in https://github.com/vercel/vercel/issues/11976 

This appears to only trigger when external packages are used that
require go versions later than 1.20.


`➜  cli git:(main) ✗ pnpm  vercel dev --cwd=../../../domain-assist/

> vercel@38.0.0 vercel
/Users/eprosimon/Developer/golang-dev-error/vercel/packages/cli
> ts-node ./src/index.ts "dev" "--cwd=../../../domain-assist/"

Vercel CLI 38.0.0
> Running Dev Command “next dev --port $PORT”
   ▲ Next.js 15.0.2
   - Local:        http://localhost:3000

 ✓ Starting...
> Ready! Available at http://localhost:3000
 ✓ Ready in 1035ms
Writing go.work contents:
use (.     <-------------------------------------------------------
  .
  ../../../..
)

go: module . listed in go.work file requires go >= 1.23.3, but go.work
implicitly requires go 1.18; to update it:
        go work use
go: module ../../../.. listed in go.work file requires go >= 1.23.3, but
go.work implicitly requires go 1.18; to update it:
        go work use
Error: Command failed: go build -ldflags -s -w -o ./vercel-dev-server-go
./...`