[tests] log command stdout/stderr on test failure (#12313)
When a unit test fails for a CLI command, we need to see the stdout/stderr from executing that command. This PR automatically renders that on test failure.

Having this would have saved me lots of time debugging test failures.

Example: This test was modified to time out. You still see the timeout error, then you see the command output.

```
 ❯ test/unit/commands/remove/index.test.ts (3) 5013ms
   ❯ remove (3) 5011ms
     ↓ [deploymentId|deploymentName] (0) [skipped]
       ↓ --yes (0) [skipped]
       ↓ --safe (0) [skipped]
       ↓ --hard (0) [skipped]
     ↓ should error if missing deployment url [skipped]
     ↓ should error without calling API for invalid names [skipped]
     × calls API to delete a project  5010ms
       ⠸ [ afterEach ]

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/unit/commands/remove/index.test.ts > remove > calls API to delete a project 
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  test/unit/commands/remove/index.test.ts > remove > calls API to delete a project 
Error: (retrieving command output because of test failure)

[STDERR]
Fetching deployment(s) "jostuwo.bv" in gavin
> Found 1 deployment for removal in gavin [9ms]
> The following deployment will be permanently removed:
  dpl_0e9f5159-f753-5781-9668-bd3f436b5c1f      https://jostuwo.bv      20ms ago      
> Are you sure? (y/N) 

[STDOUT]
(none)
 ❯ test/mocks/client.ts:270:11
    268|     // we want to throw this after calling `client.reset()`
    269|     // so the next test has a clear state
    270|     throw new Error(extraError);
       |           ^
    271|   }
    272| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯

 Test Files  1 failed (1)
      Tests  1 failed | 2 skipped (3)
   Start at  18:23:00
   Duration  7.43s (transform 749ms, setup 0ms, collect 1.56s, tests 5.01s, environment 0ms, prepare 223ms)
```